### ISSUE TITLE
User sometimes cannot create, start or stop timers

### ISSUE THREAD

**Issue by jysandy** [nilenso/time-tracker#58]
This is because the user's clock may be slightly ahead of the server's clock. The user should sync their system clock with the appropriate NTP server.

A permanent solution would be to communicate using deltas instead of absolute epochs (I want to create this timer 10s in the past). This makes the server's clock the single source of truth.

**Comment by jysandy** [comment]
As a workaround, one can run `sudo ntpd -q` to sync their system clock.

**Comment by shaaza** [comment]
I haven't switched to using deltas anywhere. For create timer, we still use client-side time. However, even if the user's clock is ahead of the server's clock, the user will be able to create a timer _now_. This is because only the spec for started-time requires the time to be _earlier than or equal to the current time_. , and the spec for created-time doesn't require this.

This means that there is the possibility of created-time being greater than started-time when the user create-and-starts a timer on a future date. Is this a problem?

**Comment by jysandy** [comment]
I think this is fine, since the created-time is mostly inconsequential. It's for bookkeeping rather than keeping track of timer state.
