### ISSUE TITLE
TimeTracker should be easy to set up

### ISSUE THREAD

**Issue by trycatcher** [nilenso/time-tracker#75]
It should not be complicated beyond a "git clone time-tracker", "cd time-tracker", "bin/dev-setup.sh"

**Comment by trycatcher** [comment]
git clone and deploy alone won't take care of the dependencies which is where most of the complications currently are

**Comment by trycatcher** [comment]
We should extract the Webpack config variable needed for Google Auth out of the repo. Even better would be to not at all use Google Auth for local setup.

**Comment by deobald** [comment]
I've edited the two above comments to replace "deploy" with "dev setup". We shouldn't get the vocabulary for these two things confused.

Dependencies can be completely automated but if we feel that's too heavy handed, they should amount to one long command, usually:

`brew install x y z`
`apt-get install x y z`

...the setup and configuration of dependencies (installing dbs, inserting seed data, copying sample configs, etc.) MUST be automated and should amount to one more command, tops.

There are exceptions to the scriptability of dev setup: passwords and keys, mostly. But otherwise the entire process should amount to a series of scripts which can either be called from a top-level script or run individually.

**Comment by kirang89** [comment]
I've made it much better with [this commit](https://github.com/nilenso/time-tracker/commit/87a3ed3a97480af4e2b949bdf05f8a2bd9d12570). Closing this for now.
